# Generated by Django 2.1.4 on 2018-12-17 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='blog_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.BlogPost'),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='cover_img_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
